services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: tictactoe
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tictactoe"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: .
    environment:
      DATABASE_URL: "postgresql://postgres:1234@postgres:5432/tictactoe?schema=public"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"

volumes:
  postgres-data: